import logging
logging.basicConfig(filename="mo092019log.txt",level=logging.DEBUG,filemode="w",format = '%(asctime)s - %(name)s - %(filename)s - %(levelname)s - %(levelno)d - %(message)s')
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")
print("python logging demo")
logging.debug("debug message")
logging.info("info message")
logging.error("error message")
logging.warning("warning message ")
logging.critical("critical message")